import {test,expect} from '@playwright/test';
import {createHash} from 'node:crypto';
import {deflateRawSync} from 'node:zlib';
import {existsSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';

test.describe.configure({mode:'serial'});
test.setTimeout(180000);

const full=new URL('../../dist/sfhs-doom-forge-v2.html',import.meta.url);
const thin=new URL('../../test-results/P07/P7-B/sfhs-doom-forge-v2-thin.html',import.meta.url);
const freedoom=resolve('..','vendor-cache','freedoom','0.13.0','data','freedoom2.wad');
const permissiveWad=resolve('..','tests','fixtures','open-pwads','order-a.wad');
const evidenceRoot=resolve('..','test-results','P07','P7-B');
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');

function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;}
function wad({magic='PWAD',lumps=[]}={}){
  const payloadBytes=lumps.reduce((sum,lump)=>sum+(lump.data?.length||0),0),directoryOffset=12+payloadBytes,output=Buffer.alloc(directoryOffset+lumps.length*16);
  output.write(magic,0,'ascii');output.writeUInt32LE(lumps.length,4);output.writeUInt32LE(directoryOffset,8);let dataAt=12;
  lumps.forEach((lump,index)=>{const data=Buffer.from(lump.data||[]),entry=directoryOffset+index*16;output.writeUInt32LE(data.length?dataAt:0,entry);output.writeUInt32LE(data.length,entry+4);output.write(String(lump.name).slice(0,8),entry+8,'ascii');data.copy(output,dataAt);dataAt+=data.length;});return output;
}
function overlappingWad(){const output=Buffer.alloc(12+12+32);output.write('PWAD');output.writeUInt32LE(2,4);output.writeUInt32LE(24,8);Buffer.from('123456789012').copy(output,12);for(const [index,name]of['FIRST','SECOND'].entries()){const at=24+index*16;output.writeUInt32LE(index?16:12,at);output.writeUInt32LE(8,at+4);output.write(name,at+8,'ascii');}return output;}
function directoryOverlapWad(){const output=Buffer.alloc(32);output.write('PWAD');output.writeUInt32LE(1,4);output.writeUInt32LE(16,8);Buffer.from('12345678').copy(output,12);output.writeUInt32LE(12,16);output.writeUInt32LE(8,20);output.write('BADDIR',24,'ascii');return output;}
function zip(entries){
  const locals=[],centrals=[];let offset=0;
  for(const entry of entries){const name=Buffer.from(entry.name),data=Buffer.from(entry.data||[]),flags=entry.flags||0,method=entry.method||0,compressed=entry.compressed||data,expandedSize=entry.expandedSize??data.length,crc=entry.crc??crc32(data),local=Buffer.alloc(30+name.length+compressed.length);local.writeUInt32LE(0x04034b50,0);local.writeUInt16LE(20,4);local.writeUInt16LE(flags,6);local.writeUInt16LE(method,8);local.writeUInt32LE(crc,14);local.writeUInt32LE(compressed.length,18);local.writeUInt32LE(expandedSize,22);local.writeUInt16LE(name.length,26);name.copy(local,30);compressed.copy(local,30+name.length);locals.push(local);
    const central=Buffer.alloc(46+name.length);central.writeUInt32LE(0x02014b50,0);central.writeUInt16LE(20,4);central.writeUInt16LE(20,6);central.writeUInt16LE(flags,8);central.writeUInt16LE(method,10);central.writeUInt32LE(crc,16);central.writeUInt32LE(compressed.length,20);central.writeUInt32LE(expandedSize,24);central.writeUInt16LE(name.length,28);central.writeUInt32LE(offset,42);name.copy(central,46);centrals.push(central);offset+=local.length;
  }
  const centralOffset=offset,centralSize=centrals.reduce((sum,item)=>sum+item.length,0),eocd=Buffer.alloc(22);eocd.writeUInt32LE(0x06054b50,0);eocd.writeUInt16LE(entries.length,8);eocd.writeUInt16LE(entries.length,10);eocd.writeUInt32LE(centralSize,12);eocd.writeUInt32LE(centralOffset,16);return Buffer.concat([...locals,...centrals,eocd]);
}
function watch(page){const pageErrors=[],consoleErrors=[],externalRequests=[],failedRequests=[];page.on('pageerror',error=>pageErrors.push(String(error)));page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text());});page.on('request',request=>{if(/^https?:/i.test(request.url()))externalRequests.push(request.url());});page.on('requestfailed',request=>failedRequests.push(`${request.url()} ${request.failure()?.errorText||''}`));return{pageErrors,consoleErrors,externalRequests,failedRequests};}
async function open(page,url=full,viewport={width:360,height:800}){await page.addInitScript(()=>Object.defineProperty(Element.prototype,'requestFullscreen',{configurable:true,value(){return Promise.resolve();}}));await page.setViewportSize(viewport);await page.goto(url.href,{waitUntil:'load',timeout:90000});await expect(page.locator('#sfhs-fullscreen-root')).toHaveAttribute('data-sfhs-fullscreen-app-root','forge-v2');await expect(page.locator('body')).toHaveAttribute('data-sfhs-p7-runtime','ready',{timeout:90000});}
async function inspect(page,name,buffer){await page.locator('#forge-inspect-file').setInputFiles({name,mimeType:'application/octet-stream',buffer});await expect.poll(()=>page.evaluate(()=>window.SFHS_WASM_TEST.analyzerSnapshot().lifecycle),{timeout:30000}).toMatch(/ready|failed/);return page.evaluate(()=>window.SFHS_WASM_TEST.analyzerSnapshot());}
function expectHygiene(hygiene){expect(hygiene.pageErrors).toEqual([]);expect(hygiene.externalRequests).toEqual([]);expect(hygiene.failedRequests).toEqual([]);expect(hygiene.consoleErrors.filter(value=>/fatal|abort|uncaught|unhandled|out of memory/i.test(value))).toEqual([]);}

test('synthetic PWAD gets exact identity, compatibility signals, and a phone-ready card',async({page})=>{
  test.skip(!existsSync(full),'Forge V2 not built');const hygiene=watch(page),fixture=wad({lumps:[{name:'MAP01'},{name:'THINGS',data:[1,2,3,4]},{name:'DEHACKED',data:[5]},{name:'S_START'},{name:'S_END'},{name:'DUP'},{name:'DUP'}]});await open(page);const before=await page.evaluate(()=>({forge:window.SFHS_WASM_TEST.forgeSnapshot(),files:Module.FS.readdir('/')}));const proof=await inspect(page,'phone-test.bin',fixture);expect(proof.lifecycle).toBe('ready');expect(proof.result.source).toEqual({name:'phone-test.bin',bytes:fixture.length,sha256:sha(fixture),type:'WAD'});expect(proof.result.permission).toEqual({status:'private-local-only',label:'Private/local only',evidence:'User-selected local file; redistribution permission is not established.'});expect(proof.result.wads[0]).toMatchObject({kind:'PWAD',lumpCount:7,targetGame:'doom2',embeddedDehacked:true,duplicateCount:1,loadingMethod:'Ordinary PWAD (-file)'});expect(proof.result.compatibility.status).toBe('likely-compatible');expect(proof.result.launchable).toBe(false);expect(proof.result.storedBytes).toBe(0);expect(proof.mainInvocations).toBe(0);const after=await page.evaluate(()=>({forge:window.SFHS_WASM_TEST.forgeSnapshot(),files:Module.FS.readdir('/'),scroll:[scrollX,scrollY,document.documentElement.scrollWidth,innerWidth,document.documentElement.scrollHeight,innerHeight],card:(()=>{const value=document.getElementById('inspection-card').getBoundingClientRect(),region=document.getElementById('game-region').getBoundingClientRect(),picker=document.getElementById('forge-inspect-picker').getBoundingClientRect();return{value:{x:value.x,y:value.y,right:value.right,bottom:value.bottom},region:{x:region.x,y:region.y,right:region.right,bottom:region.bottom},pickerHeight:picker.height,startScroll:document.getElementById('forge-start-card').scrollHeight,startClient:document.getElementById('forge-start-card').clientHeight};})()}));expect(after.files).toEqual(before.files);expect(after.forge).toEqual(before.forge);expect(after.scroll[0]).toBe(0);expect(after.scroll[1]).toBe(0);expect(after.scroll[2]).toBeLessThanOrEqual(after.scroll[3]);expect(after.scroll[4]).toBeLessThanOrEqual(after.scroll[5]);expect(after.card.value.x).toBeGreaterThanOrEqual(after.card.region.x);expect(after.card.value.right).toBeLessThanOrEqual(after.card.region.right+1);expect(after.card.pickerHeight).toBeGreaterThanOrEqual(44);await expect(page.locator('#inspection-fields')).toContainText('Private/local only');await page.screenshot({path:resolve(evidenceRoot,'portrait-wad-inspection.png')});expectHygiene(hygiene);writeFileSync(resolve(evidenceRoot,'portrait-wad-inspection.json'),JSON.stringify({proof,after,hygiene},null,2));
});

test('real permissive PWAD fixture is identified by bytes',async({page})=>{
  test.skip(!existsSync(full)||!existsSync(permissiveWad),'artifact or permissive fixture unavailable');await open(page);const fixture=readFileSync(permissiveWad),proof=await inspect(page,'renamed.data',fixture);expect(proof.lifecycle).toBe('ready');expect(proof.result.source.type).toBe('WAD');expect(proof.result.source.sha256).toBe(sha(fixture));expect(proof.result.wads[0].directoryValid).toBe(true);expect(proof.mainInvocations).toBe(0);
});

test('safe ZIP reports entries, docs, ignored executable content, and its contained WAD',async({page})=>{
  const inner=wad({lumps:[{name:'E1M1'},{name:'THINGS',data:[7,8]}]}),fixture=zip([{name:'mods/episode.dat',data:inner,method:8,compressed:deflateRawSync(inner)},{name:'README.txt',data:Buffer.from('permissive fixture documentation')},{name:'tools/setup.exe',data:Buffer.from('never execute')}]);await open(page);const proof=await inspect(page,'bundle.renamed',fixture);expect(proof.lifecycle).toBe('ready');expect(proof.result.source).toEqual({name:'bundle.renamed',bytes:fixture.length,sha256:sha(fixture),type:'ZIP'});expect(proof.result.archive.entryCount).toBe(3);expect(proof.result.archive.entries[0].method).toBe(8);expect(proof.result.archive.documents).toContain('README.txt');expect(proof.result.archive.ignored).toContainEqual({path:'tools/setup.exe',reason:'executable-content'});expect(proof.result.wads[0]).toMatchObject({name:'episode.dat',kind:'PWAD',targetGame:'doom'});expect(proof.result.compatibility.status).toBe('likely-compatible');expect(proof.mainInvocations).toBe(0);await page.screenshot({path:resolve(evidenceRoot,'portrait-zip-inspection.png')});
});

test('advanced-port markers produce an explicit unsupported classification',async({page})=>{
  const fixture=wad({lumps:[{name:'MAP01'},{name:'TEXTMAP',data:[1]},{name:'ENDMAP'}]});await open(page);const proof=await inspect(page,'advanced.wad',fixture);expect(proof.lifecycle).toBe('ready');expect(proof.result.wads[0].unsupportedSignals).toEqual(['TEXTMAP','ENDMAP']);expect(proof.result.compatibility).toMatchObject({status:'unsupported-by-engine',label:'Unsupported by this engine',confidence:'high'});await expect(page.locator('#inspection-compatibility')).toHaveAttribute('data-status','unsupported-by-engine');
});

test('malformed WADs and unsupported bytes fail closed without launch or storage',async({page})=>{
  await open(page);const malformed=Buffer.alloc(12);malformed.write('PWAD');malformed.writeUInt32LE(1,4);malformed.writeUInt32LE(9999,8);for(const item of[{name:'bounds.wad',buffer:malformed,code:'wad-directory-bounds'},{name:'directory-overlap.wad',buffer:directoryOverlapWad(),code:'wad-directory-overlap'},{name:'overlap.wad',buffer:overlappingWad(),code:'wad-overlap'},{name:'image.png',buffer:Buffer.from('not a wad or zip'),code:'unsupported-type'}]){const proof=await inspect(page,item.name,item.buffer);expect(proof).toMatchObject({lifecycle:'failed',storedBytes:0,launchable:false,mainInvocations:0,error:{code:item.code,sha256:sha(item.buffer),storedBytes:0,launchable:false}});await expect(page.locator('#inspection-compatibility')).toHaveText('Inspection rejected');await expect(page.locator('#inspection-fields')).toContainText(sha(item.buffer));}
});

test('ZIP traversal, encryption, expansion abuse, and duplicate paths are bounded',async({page})=>{
  await open(page);const tooMany=Buffer.alloc(22);tooMany.writeUInt32LE(0x06054b50,0);tooMany.writeUInt16LE(513,8);tooMany.writeUInt16LE(513,10);for(const item of[{name:'traversal.zip',buffer:zip([{name:'../escape.wad',data:wad()}]),code:'zip-traversal'},{name:'absolute.zip',buffer:zip([{name:'/escape.wad',data:wad()}]),code:'zip-path'},{name:'encrypted.zip',buffer:zip([{name:'locked.wad',data:wad(),flags:1}]),code:'zip-encrypted'},{name:'ratio.zip',buffer:zip([{name:'bomb.wad',data:Buffer.from([0]),compressed:Buffer.from([0]),expandedSize:1000,crc:0}]),code:'zip-ratio'},{name:'count.zip',buffer:tooMany,code:'zip-file-count'}]){const proof=await inspect(page,item.name,item.buffer);expect(proof).toMatchObject({lifecycle:'failed',mainInvocations:0,error:{code:item.code,storedBytes:0,launchable:false}});}const duplicate=zip([{name:'same.wad',data:wad({lumps:[{name:'MAP01'}]})},{name:'same.wad',data:wad({lumps:[{name:'MAP02'}]})},{name:'nested/archive.zip',data:zip([])}]),proof=await inspect(page,'duplicate.zip',duplicate);expect(proof.lifecycle).toBe('ready');expect(proof.result.archive.duplicatePaths).toEqual(['same.wad']);expect(proof.result.archive.nested).toEqual(['nested/archive.zip']);expect(proof.result.archive.ignored).toContainEqual({path:'nested/archive.zip',reason:'nested-archive'});expect(proof.result.compatibility.status).toBe('manual-recipe-required');
});

test('large WAD analysis stays off the main thread and remains responsive',async({page})=>{
  const fixture=wad({lumps:[{name:'MAP01'},{name:'BIGDATA',data:Buffer.alloc(16*1024*1024,0x5a)}]});await open(page);await page.evaluate(()=>{window.__p7bFrames=0;window.__p7bFrameStop=false;const tick=()=>{window.__p7bFrames+=1;if(!window.__p7bFrameStop)requestAnimationFrame(tick);};requestAnimationFrame(tick);});const proof=await inspect(page,'large.wad',fixture);const frames=await page.evaluate(()=>{window.__p7bFrameStop=true;return window.__p7bFrames;});expect(proof.lifecycle).toBe('ready');expect(proof.result.source.sha256).toBe(sha(fixture));expect(frames).toBeGreaterThan(3);expect(proof.result.durationMs).toBeLessThan(15000);
});

test('landscape inspection is contained and built-in V16 still launches exactly once',async({page})=>{
  const hygiene=watch(page),fixture=wad({lumps:[{name:'MAP01'}]});await open(page,full,{width:915,height:412});const proof=await inspect(page,'landscape.wad',fixture);expect(proof.lifecycle).toBe('ready');await expect(page.locator('#sfhs-mobile-controls-root')).toBeHidden();const layout=await page.evaluate(()=>{const card=document.getElementById('forge-start-card'),region=document.getElementById('game-region').getBoundingClientRect(),button=document.getElementById('start-doom').getBoundingClientRect();return{region:{left:region.left,top:region.top,right:region.right,bottom:region.bottom},card:{scrollHeight:card.scrollHeight,clientHeight:card.clientHeight},button:{left:button.left,top:button.top,right:button.right,bottom:button.bottom},page:[scrollX,scrollY,document.documentElement.scrollWidth,innerWidth,document.documentElement.scrollHeight,innerHeight]};});expect(layout.button.left).toBeGreaterThanOrEqual(layout.region.left);expect(layout.button.right).toBeLessThanOrEqual(layout.region.right+1);expect(layout.page[0]).toBe(0);expect(layout.page[1]).toBe(0);await page.screenshot({path:resolve(evidenceRoot,'landscape-inspection.png')});await page.getByRole('button',{name:'Play built-in Freedoom'}).click();await expect.poll(()=>page.evaluate(()=>window.SFHSDoomMobileControls?.snapshot().game?.active),{timeout:30000}).toBe(1);await expect(page.locator('#sfhs-mobile-controls-root')).toBeVisible();await expect.poll(()=>page.evaluate(()=>Module.SDL2?.audioContext?.state||null),{timeout:20000}).toBe('running');const ending=await page.evaluate(()=>({forge:window.SFHS_WASM_TEST.forgeSnapshot(),analyzer:window.SFHS_WASM_TEST.analyzerSnapshot(),world:[canvas.width,canvas.height],hud:[document.getElementById('doom-status-canvas').width,document.getElementById('doom-status-canvas').height]}));expect(ending.forge.mainInvocations).toBe(1);expect(ending.analyzer.launchable).toBe(false);expect(ending.world).toEqual([320,200]);expect(ending.hud).toEqual([320,32]);expectHygiene(hygiene);writeFileSync(resolve(evidenceRoot,'landscape-inspection.json'),JSON.stringify({proof,layout,ending,hygiene},null,2));
});

test('thin analyzer cannot satisfy or mutate the exact-base mount gate',async({page})=>{
  test.skip(!existsSync(thin)||!existsSync(freedoom),'thin artifact or Freedoom unavailable');await open(page,thin);await expect.poll(()=>page.evaluate(()=>window.SFHS_WASM_TEST.forgeSnapshot().mountStage)).toBe('awaiting-file');const fixture=wad({lumps:[{name:'MAP01'}]}),proof=await inspect(page,'addon.wad',fixture);expect(proof.lifecycle).toBe('ready');expect(proof.mountStage).toBe('awaiting-file');expect(proof.mainInvocations).toBe(0);await expect(page.getByRole('button',{name:'Play built-in Freedoom'})).toBeHidden();await page.locator('#forge-base-file').setInputFiles(freedoom);await expect.poll(()=>page.evaluate(()=>window.SFHS_WASM_TEST.forgeSnapshot().mountStage),{timeout:90000}).toBe('ready');expect((await page.evaluate(()=>window.SFHS_WASM_TEST.analyzerSnapshot())).result.source.sha256).toBe(sha(fixture));
});

test.beforeAll(()=>mkdirSync(evidenceRoot,{recursive:true}));
